import Anthropic from '@anthropic-ai/sdk';
import type { Arrangement, LevelId } from '../types';
import type { Step } from '../sheet/steps';

const KEY_STORAGE = 'psg.anthropicKey';
const MODEL = 'claude-opus-5';

export function getApiKey(): string | null {
  try { return localStorage.getItem(KEY_STORAGE); } catch { return null; }
}
export function setApiKey(key: string | null): void {
  try { key ? localStorage.setItem(KEY_STORAGE, key) : localStorage.removeItem(KEY_STORAGE); } catch { /* private mode */ }
}

function client(): Anthropic {
  const apiKey = getApiKey();
  if (!apiKey) throw new Error('No Anthropic API key set. Add one in Settings.');
  // The key is the user's own and lives only in their browser; direct browser access is intentional.
  return new Anthropic({ apiKey, dangerouslyAllowBrowser: true });
}

function textOf(res: Anthropic.Message): string {
  return res.content.filter((b): b is Anthropic.TextBlock => b.type === 'text').map((b) => b.text).join('\n');
}

function extractJson<T>(text: string): T {
  const m = /```(?:json)?\s*([\s\S]*?)```/.exec(text);
  const raw = m ? m[1] : text;
  const start = raw.search(/[[{]/);
  return JSON.parse(raw.slice(start)) as T;
}

/** Rewrite the rule-based steps with friendlier coaching, keeping the actions intact. */
export async function enrichSteps(arr: Arrangement, levelId: LevelId, steps: Step[]): Promise<Step[]> {
  const c = client();
  const level = arr.levels[levelId];
  const summary = {
    title: arr.title, key: level.key.name, bpm: arr.bpm, timeSignature: `${arr.timeSig.num}/${arr.timeSig.den}`,
    level: `${levelId} - ${level.name}`, bars: arr.totalBars,
    chords: [...new Set(level.chords.map((ch) => ch.name))],
    sections: arr.sections.map((s) => ({ label: s.label, bars: `${s.startBar + 1}-${s.endBar + 1}`, repeatOf: s.repeatOf })),
    steps: steps.map((s, i) => ({ index: i, title: s.title, body: s.body })),
  };
  const res = await c.messages.create({
    model: MODEL,
    max_tokens: 8000,
    system: 'You are a patient piano teacher writing for an adult self-learner who cannot read sheet music. ' +
      'You will receive a JSON description of a piece and a list of practice steps generated by rules. ' +
      'Rewrite each step body in warm, concrete, plain language (2-4 sentences): what to do, what to listen for, one common mistake to avoid. ' +
      'Keep every note name and bar number exactly as given. Do not add or remove steps. ' +
      'Respond with only a JSON array of objects {"index": number, "title": string, "body": string}.',
    messages: [{ role: 'user', content: JSON.stringify(summary) }],
  });
  if (res.stop_reason === 'refusal') throw new Error('The model declined this request.');
  const items = extractJson<{ index: number; title?: string; body: string }[]>(textOf(res));
  const out = steps.map((s) => ({ ...s }));
  for (const it of items) if (out[it.index]) { out[it.index].body = it.body; if (it.title) out[it.index].title = it.title; }
  return out;
}

/** When MIDI search finds nothing, ask for alternate spellings / original titles to try. */
export async function suggestSearchTerms(query: string): Promise<string[]> {
  const c = client();
  const res = await c.messages.create({
    model: MODEL,
    max_tokens: 1000,
    system: 'The user is searching a MIDI-file site by song name and got no results. Suggest up to 5 alternative search strings: ' +
      'the original-language title, the composer or artist name plus title, common misspellings fixed, or the well-known nickname of the piece. ' +
      'Respond with only a JSON array of strings.',
    messages: [{ role: 'user', content: query }],
  });
  if (res.stop_reason === 'refusal') return [];
  return extractJson<string[]>(textOf(res)).filter((s) => typeof s === 'string').slice(0, 5);
}
