import puppeteer from 'puppeteer-core';
const SP = process.argv[2];
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true,
  args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--window-size=1400,900'] });
const page = await browser.newPage();
await page.setViewport({ width: 1400, height: 900 });
const logs = [];
page.on('console', (m) => { if (['error', 'warning', 'warn'].includes(m.type()) && !/GL Driver|ReadPixels/.test(m.text())) logs.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', (e) => logs.push(`[pageerror] ${e.message}`));
await page.goto('http://localhost:5179/', { waitUntil: 'networkidle0' });
await page.click('#btn-enable-audio');
await page.click('#level-picker [data-level="3"]');
await page.click('#mode-seg [data-mode="learn"]');
await page.click('#btn-play');
await new Promise((r) => setTimeout(r, 1500));
const status = await page.$eval('#status', (e) => e.textContent);
await page.screenshot({ path: `${SP}/u1-practice-wait.png` });
await page.click('#btn-stop');
await page.type('#search-input', 'fur elise');
await page.click('#search-form button');
await page.waitForFunction(() => document.querySelectorAll('#results .res-item').length > 3, { timeout: 20000 });
const bit = await page.$$('#results .res-item');
await bit[2].click();
await page.waitForFunction(() => document.querySelector('#song-info')?.textContent?.includes('bitmidi'), { timeout: 20000 });
await new Promise((r) => setTimeout(r, 500));
const info = await page.$eval('#song-info', (e) => e.textContent);
await page.click('#level-picker [data-level="2"]');
await new Promise((r) => setTimeout(r, 500));
await page.screenshot({ path: `${SP}/u2-furelise-l2.png` });
console.log(JSON.stringify({ status, info, logs }));
await browser.close();
